### ISSUE TITLE
this coin is dead

### ISSUE THREAD

**Issue by yquan162** [yquan162/clementscoin#3]
United forever in friendship and la:b:our, Our mighty repu:b:lics will ever endure. The Great Soviet Union will live through the ages. The dream of a people their fortress secure. Long live our Soviet motherland, :b:uilt :b:y the people's mighty hand. Long live our people, united and free. Strong in our friendship tried :b:y fire. Long may our crimson flag inspire, Shining in glory for all men to see. Through days dark and stormy where Great Lenin lead us Our eyes saw the :b:right sun of freedom a:b:ove And Stalin our leader with faith in the people, Inspired us to :b:uild up the land that we love. Long live our Soviet motherland, :b:uilt :b:y the people's mighty hand. Long live our people, united and free. Strong in our friendship tried :b:y fire. Long may our crimson flag inspire, Shining in glory for all men to see. We fought for the future, destroyed the invaders, And :b:rought to our homeland the laurels of fame. Our glory will live in the memory of nations And all generations will honour her name. Long live our Soviet motherland, :b:uilt :b:y the people's mighty hand. Long live our people, united and free. Strong in our friendship tried :b:y fire. Long may our crimson flag inspire, Shining in glory for all men to see.

**Comment by yquan162** [comment]
Un:b:reaka:b:le Union of free:b:orn Repu:b:lics, Great Russia has welded forever to stand. Created in struggle :b:y will of the people, United and mighty, our Soviet land! Sing to the Motherland, home of the free, :b:ulwark of peoples in :b:rotherhood strong. O Party of Lenin, the strength of the people, To Communism's triumph lead us on! Through tempests the sunrays of freedom have cheered us, Along the new path where great Lenin did lead. To a righteous cause he raised up the peoples, Inspired them to la:b:our and valourous deed. Sing to the Motherland, home of the free, :b:ulwark of peoples in :b:rotherhood strong. O Party of Lenin, the strength of the people, To Communism's triumph lead us on! In the victory of Communism's immortal ideal, We see the future of our dear land. And to her fluttering scarlet :b:anner, Selflessly true we always shall stand! Sing to the Motherland, home of the free, :b:ulwark of peoples in :b:rotherhood strong. O Party of Lenin, the strength of the people, To Communism's triumph lead us on!

**Comment by yquan162** [comment]
:b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b::b:

**Comment by PotatoCurry** [comment]
no me
